repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # 自动修复
        types_or: [python, pyi, jupyter]
default_language_version:
  python: python3.10 # or python3

exclude: migrations
